### ISSUE TITLE
TODO List 

### ISSUE THREAD

**Issue by FaberSanZ** [FaberSanZ/Vultaik#7]
_This is an overview of some major bullet points for improvements or unimplemented features in **Vultaik**:_

- [ ] Resource state transitioning: This is very fragile and needs improvement.

- [ ] Memory allocator:

- [ ] Multi-sampling support:

- [x] Push constants:

- [ ] Ray Tracing:

- [ ] Conservative rasterization:

- [ ] Multiview rendering: 

- [ ] Conditional rendering 

- [ ] Shading rate

- [x] Descriptor indexing: This is very fragile and needs improvement.

- [ ] Timeline semaphore

- [ ] Synchronization2: `VK_KHR_synchronization2`

- [x] GPU-Assisted Validation

- [x] Compute Shader

- [x] Geometry Shader

- [x] Tessellation Shader

- [ ] Instancing, Indirect drawing

- [ ] Post-AA (FXAA, SMAA and TAA)

- [ ] Multithreaded rendering

- [x] Automatic descriptor set management

- [x] Shader reflection with [SPIRV-Cross](https://github.com/KhronosGroup/SPIRV-Cross)

- [x] Vulkan HLSL for shaders, shaders are compiled in runtime with [DirectXShaderCompiler](https://github.com/microsoft/DirectXShaderCompiler)
